# Generated by Django 4.0.3 on 2022-03-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biogenesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityshots',
            options={'verbose_name': 'Кадр животного', 'verbose_name_plural': 'Кадры животных'},
        ),
    ]
