# Generated by Django 4.0.3 on 2022-03-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biogenesis', '0003_entityshots_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityshots',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='biogenesis.entity', verbose_name='Существа'),
        ),
    ]
