# Generated by Django 3.0 on 2022-03-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biogenesis', '0006_auto_20220323_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityshots',
            name='description',
        ),
        migrations.AlterField(
            model_name='entity',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
        migrations.AlterField(
            model_name='entityshots',
            name='title',
            field=models.CharField(default=True, max_length=150, verbose_name='Заголовок'),
        ),
    ]
