# Generated by Django 3.0 on 2022-03-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biogenesis', '0008_remove_entity_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='poster',
            field=models.ImageField(null=True, upload_to='entitys/', verbose_name='Постер'),
        ),
    ]
