# Generated by Django 3.0 on 2022-03-31 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biogenesis', '0009_entity_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='poster',
        ),
    ]
