# Generated by Django 3.0 on 2022-04-05 08:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biogenesis', '0011_entity_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
