# Generated by Django 3.0 on 2022-05-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biogenesis', '0012_auto_20220405_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntityShots',
        ),
    ]
