# Generated by Django 3.0 on 2022-05-11 06:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biogenesis', '0013_delete_entityshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
