# Generated by Django 3.0 on 2022-05-11 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biogenesis', '0014_auto_20220511_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название книги')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='Book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biogenesis.Book', verbose_name='Книга'),
        ),
    ]
